# -*- coding: utf-8 -*-
"""
Created on Tue Dec  8 23:18:32 2020

@author: user
"""

import os
import pandas as pd

os.chdir("C:\workingDirectory\\")  

data1 = pd.read_csv("wp001_data_008R_adverse.txt",
                    sep="_",
                    header=None,
                    dtype={5:str, 8:str, 10:str},
                    skip_blank_lines=True,
                    keep_default_na=False,
                    usecols=[*range(0,16)])

data2 = pd.read_csv("wp001_data_008R_disclaimer.txt",
                    sep="_",
                    header=None,
                    dtype={5:str, 8:str, 10:str},
                    skip_blank_lines=True,
                    keep_default_na=False,
                    usecols=[*range(0,16)])

data3 = pd.read_csv("wp001_data_008R_qualified.txt",
                    sep="_",
                    header=None,
                    dtype={5:str, 8:str, 10:str},
                    skip_blank_lines=True,
                    keep_default_na=False,
                    usecols=[*range(0,16)])
                    # https://stackoverflow.com/questions/35400861/pandas-read-table-usecols-error-with
        
data = data1.append(data2)
data = data.append(data3)

data["key1"] = data[5] + data[6].str.slice(stop=10) + data[8] + data[10]
data["key2"] = data[2] + data[5] + data[8] + data[10]
data["duplc1"] = data.duplicated(subset=["key1"], keep=False)
data["duplc2"] = data.duplicated(subset=["key2"], keep=False)

isTrue1 = data[data["duplc1"] == True]
isTrue2 = data[data["duplc2"] == True]
data1 = data.drop_duplicates(subset=["key1"])
dataOut = data1.drop_duplicates(subset=["key2"])

result = dataOut[["key2",3, 5, 15]]
result.to_csv("wp001_data_008R_output.txt", sep="\t")
